### ISSUE TITLE
Cannot see add-in in Outlook

### ISSUE THREAD

**Issue by niallermoran** [OfficeDev/Outlook-Add-in-RepoReport#4]
Hi, I have followed all of the instructions and added the BillMaker add-in via the manage add-ins portal but I cannot see the buttons anywhere in Outlook client. I am running the gulp web server and I have trusted the certificate.

Any ideas. BTW, when I open a calendar item I can see other add-ins that I just installed like Uber.

Any help appreciated

**Comment by martellaj** [comment]
Hey, @niallermoran, sorry to hear you're having issues with the Bill Maker add-in. Please open an issue in that repo ([here](https://github.com/OfficeDev/Outlook-Add-in-BillMaker/issues)) with some more details (like what Outlook client you're using) and someone will be able to help you out.
