### ISSUE TITLE
VS Setup and debugging

### ISSUE THREAD

**Issue by lazyspark** [OfficeDev/Outlook-Add-in-RepoReport#5]
Hi,

I was able to setup the project. But to understand the project I wanted to trigger this through Visual studio and maybe setup breakpoint to understand the application flow. What would be the way to go for it? Is there a base template that creates similar apps in VS? 

Thanks,
Sawan

**Comment by Rick-Kirkham** [comment]
Sorry that we took so long to respond. Unfortunately, there is no VS template that would match this angular sample.
